/*
* generated by Xtext
*/
package jp.ac.jaist.kslab.sb.marte.spec.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SpecDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("jp/ac/jaist/kslab/sb/marte/spec/parser/antlr/internal/InternalSpecDsl.tokens");
	}
}
