/*
* generated by Xtext
*/
package jp.ac.jaist.kslab.sb.marte.spec.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import jp.ac.jaist.kslab.sb.marte.spec.services.SpecDslGrammarAccess;

public class SpecDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SpecDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected jp.ac.jaist.kslab.sb.marte.spec.parser.antlr.internal.InternalSpecDslParser createParser(XtextTokenStream stream) {
		return new jp.ac.jaist.kslab.sb.marte.spec.parser.antlr.internal.InternalSpecDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public SpecDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SpecDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
