/*
 * generated by Xtext
 */
package jp.ac.jaist.kslab.sb.marte.merge;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MergeDslRuntimeModule extends jp.ac.jaist.kslab.sb.marte.merge.AbstractMergeDslRuntimeModule {

}
