/*
 * generated by Xtext
 */
package jp.ac.jaist.kslab.sb.marte.dsl.circuit.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CircuitDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return jp.ac.jaist.kslab.sb.marte.dsl.circuit.ui.internal.CircuitDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return jp.ac.jaist.kslab.sb.marte.dsl.circuit.ui.internal.CircuitDslActivator.getInstance().getInjector("jp.ac.jaist.kslab.sb.marte.dsl.circuit.CircuitDsl");
	}
	
}
