/*
* generated by Xtext
*/
package jp.ac.jaist.kslab.sb.marte.dsl.circuit.ui.contentassist;

import jp.ac.jaist.kslab.sb.marte.dsl.circuit.ui.contentassist.AbstractCircuitDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CircuitDslProposalProvider extends AbstractCircuitDslProposalProvider {

}
