/*
 * generated by Xtext
 */
package jp.ac.jaist.kslab.sb.marte.spec;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SpecDslRuntimeModule extends jp.ac.jaist.kslab.sb.marte.spec.AbstractSpecDslRuntimeModule {

}
