/*
* generated by Xtext
*/
package jp.ac.jaist.kslab.sb.marte.dsl.circuit.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import jp.ac.jaist.kslab.sb.marte.dsl.circuit.services.CircuitDslGrammarAccess;

public class CircuitDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CircuitDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected jp.ac.jaist.kslab.sb.marte.dsl.circuit.parser.antlr.internal.InternalCircuitDslParser createParser(XtextTokenStream stream) {
		return new jp.ac.jaist.kslab.sb.marte.dsl.circuit.parser.antlr.internal.InternalCircuitDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "HwCircuitDiagram";
	}
	
	public CircuitDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CircuitDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
