/*
 * generated by Xtext
 */
package jp.ac.jaist.kslab.sb.marte.dsl.circuit.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CircuitDslUiModule extends jp.ac.jaist.kslab.sb.marte.dsl.circuit.ui.AbstractCircuitDslUiModule {
	public CircuitDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
