/*
 * generated by Xtext
 */
package jp.ac.jaist.kslab.sb.marte.dsl.circuit.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.IGenerator
import org.eclipse.xtext.generator.IFileSystemAccess

class CircuitDslGenerator implements IGenerator {
	
	override void doGenerate(Resource resource, IFileSystemAccess fsa) {
	}
	

	
}
