/*
 * generated by Xtext
 */
package jp.ac.jaist.kslab.sb.marte.dsl.circuit;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CircuitDslRuntimeModule extends jp.ac.jaist.kslab.sb.marte.dsl.circuit.AbstractCircuitDslRuntimeModule {

}
