datasheet atmega2560 {
	protocol i2c{}
	mcu atmega640{
		pins {p1,p2}
		port PortA {p1,p2}
		peripheral i2c impl i2c{
			
		}
		sfrs {
			UDR3 : "0x136",
			UBRR3H : "0x135",
			UBRR3L : "0x134",
			UCSR3C : "0x132",
			UCSR3B : "0x131",
			UCSR3A : "0x130",
			OCR5CH : "0x12D",
			OCR5CL : "0x12C",
			OCR5BH : "0x12B",
			OCR5BL : "0x12A",
			OCR5AH : "0x129",
			OCR5AL : "0x128",
			ICR5H : "0x127",
			ICR5L : "0x126",
			TCNT5H : "0x125",
			TCNT5L : "0x124",
			TCCR5C : "0x122",
			TCCR5B : "0x121",
			TCCR5A : "0x120",
			PORTL : "0x10B",
			DDRL : "0x10A",
			PINL : "0x109",
			PORTK : "0x108",
			DDRK : "0x107",
			PINK : "0x106",
			PORTJ : "0x105",
			DDRJ : "0x104",
			PINJ : "0x103",
			PORTH : "0x102",
			DDRH : "0x101",
			PINH : "0x100",
			UDR2 : "0xD6",
			UBRR2H : "0xD5",
			UBRR2L : "0xD4",
			UCSR2C : "0xD2",
			UCSR2B : "0xD1",
			UCSR2A : "0xD0",
			UDR1 : "0xCE",
			UBRR1H : "0xCD",
			UBRR1L : "0xCC",
			UCSR1C : "0xCA",
			UCSR1B : "0xC9",
			UCSR1A : "0xC8",
			UDR0 : "0xC6",
			UBRR0H : "0xC5",
			UBRR0L : "0xC4",
			UCSR0C : "0xC2",
			UCSR0B : "0xC1",
			UCSR0A : "0xC0",
			TWAMR : "0xBD",
			TWCR : "0xBC",
			TWDR : "0xBB",
			TWAR : "0xBA",
			TWSR : "0xB9",
			TWBR : "0xB8",
			ASSR : "0xB6",
			OCR2B : "0xB4",
			OCR2A : "0xB3",
			TCNT2 : "0xB2",
			TCCR2B : "0xB1",
			TCCR2A : "0xB0",
			OCR4CH : "0xAD",
			OCR4CL : "0xAC",
			OCR4BH : "0xAB",
			OCR4BL : "0xAA",
			OCR4AH : "0xA9",
			OCR4AL : "0xA8",
			ICR4H : "0xA7",
			ICR4L : "0xA6",
			TCNT4H : "0xA5",
			TCNT4L : "0xA4",
			TCCR4C : "0xA2",
			TCCR4B : "0xA1",
			TCCR4A : "0xA0",
			OCR3CH : "0x9D",
			OCR3CL : "0x9C",
			OCR3BH : "0x9B",
			OCR3BL : "0x9A",
			OCR3AH : "0x99",
			OCR3AL : "0x98",
			ICR3H : "0x97",
			ICR3L : "0x96",
			TCNT3H : "0x95",
			TCNT3L : "0x94",
			TCCR3C : "0x92",
			TCCR3B : "0x91",
			TCCR3A : "0x90",
			OCR1CH : "0x8D",
			OCR1CL : "0x8C",
			OCR1BH : "0x8B",
			OCR1BL : "0x8A",
			OCR1AH : "0x89",
			OCR1AL : "0x88",
			ICR1H : "0x87",
			ICR1L : "0x86",
			TCNT1H : "0x85",
			TCNT1L : "0x84",
			TCCR1C : "0x82",
			TCCR1B : "0x81",
			TCCR1A : "0x80",
			DIDR1 : "0x7F",
			DIDR0 : "0x7E",
			DIDR2 : "0x7D",
			ADMUX : "0x7C",
			ADCSRB : "0x7B",
			ADCSRA : "0x7A",
			ADCH : "0x79",
			ADCL : "0x78",
			XMCRB : "0x75",
			XMCRA : "0x74",
			TIMSK5 : "0x73",
			TIMSK4 : "0x72",
			TIMSK3 : "0x71",
			TIMSK2 : "0x70",
			TIMSK1 : "0x6F",
			TIMSK0 : "0x6E",
			PCMSK2 : "0x6D",
			PCMSK1 : "0x6C",
			PCMSK0 : "0x6B",
			EICRB : "0x6A",
			EICRA : "0x69",
			PCICR : "0x68",
			OSCCAL : "0x66",
			PRR1 : "0x65",
			PRR0 : "0x64",
			CLKPR : "0x61",
			WDTCSR : "0x60",
			SREG : "0x5F",
			SPH : "0x5E",
			SPL : "0x5D",
			EIND : "0x5C",
			RAMPZ : "0x5B",
			SPMCSR : "0x57",
			MCUCR : "0x55",
			MCUSR : "0x54",
			SMCR : "0x53",
			OCDR : "0x51",
			ACSR : "0x50",
			SPDR : "0x4E",
			SPSR : "0x4D",
			SPCR : "0x4C",
			GPIOR2 : "0x4B",
			GPIOR1 : "0x4A",
			OCR0B : "0x48",
			OCR0A : "0x47",
			TCNT0 : "0x46",
			TCCR0B : "0x45",
			TCCR0A : "0x44",
			GTCCR : "0x43",
			EEARH : "0x42",
			EEARL : "0x41",
			EEDR : "0x40",
			EECR : "0x3F",
			GPIOR0 : "0x3E",
			EIMSK : "0x3D",
			EIFR : "0x3C",
			PCIFR : "0x3B",
			TIFR5 : "0x3A",
			TIFR4 : "0x39",
			TIFR3 : "0x38",
			TIFR2 : "0x37",
			TIFR1 : "0x36",
			TIFR0 : "0x35",
			PORTG : "0x34",
			DDRG : "0x33",
			PING : "0x32",
			PORTF : "0x31",
			DDRF : "0x30",
			PINF : "0x2F",
			PORTE : "0x2E",
			DDRE : "0x2D",
			PINE : "0x2C",
			PORTD : "0x2B",
			DDRD : "0x2A",
			PIND : "0x29",
			PORTC : "0x28",
			DDRC : "0x27",
			PINC : "0x26",
			PORTB : "0x25",
			DDRB : "0x24",
			PINB : "0x23",
			PORTA : "0x22",
			DDRA : "0x21",
			PINA : "0x20"			
		}

		package TQFP{
			PG5(1){OC0B},
			PE0(2){RXD0,PCINT8},
			PE1(3){TXD0},
			PE2(4){XCK0,AIN0},
			PE3(5){OC3A,AIN1},
			PE4(6){OC3B,INT4},
			PE5(7){OC3C,INT5},
			PE6(8){T3,INT6},
			PE7(9){CLKO,ICP3,INT7},
			VCC(10),
			GND(11),
			PH0(12){RXD2},
			PH1(13){TXD2},
			PH2(14){XCK2},
			PH3(15){OC4A},
			PH4(16){OC4B},
			PH5(17){OC4C},
			PH6(18){OC2B},
			PB0(19){SS,PCINT0},
			PB1(20){SCK,PCINT1},
			PB2(21){MOSI,PCINT2},
			PB3(22){MISO,PCINT3},
			PB4(23){OC2A,PCINT4},
			PB5(24){OC1A,PCINT5},
			PB6(25){OC1B,PCINT6},
			PB7(26){OC0A,OC1C,PCINT7},
			PH7(27){T4},
			PG3(28){TOSC2},
			PG4(29){TOSC1},
			RESET(30),
			VCC(31),
			GND(32),
			XTAL2(33),
			XTAL1(34),
			PL0(35){ICP4},
			PL1(36){ICP5},
			PL2(37){T5},
			PL3(38){OC5A},
			PL4(39){OC5B},
			PL5(40){OC5C},
			PL6(41),
			PL7(42),
			PD0(43){SCL,INT0},
			PD1(44){SDA,INT1},
			PD2(45){RXD1,INT2},
			PD3(46){TXD1,INT3},
			PD4(47){ICP1},
			PD5(48){XCK1},
			PD6(49){T1},
			PD7(50){T0},
			PG0(51){WR},
			PG1(52){RD},
			PC0(53){A8},
			PC1(54){A9},
			PC2(55){A10},
			PC3(56){A11},
			PC4(57){A12},
			PC5(58){A13},
			PC6(59){A14},
			PC7(60){A15},
			VCC(61),
			GND(62),
			PJ0(63){RXD3,PCINT9},
			PJ1(64){TXD3,PCINT10},
			PJ2(65){XCK3,PCINT11},
			PJ3(66){PCINT12},
			PJ4(67){PCINT13},
			PJ5(68){PCINT14},
			PJ6(69){PCINT15},
			PG2(70){ALE},
			PA7(71){AD7},
			PA6(72){AD6},
			PA5(73){AD5},
			PA4(74){AD4},
			PA3(75){AD3},
			PA2(76){AD2},
			PA1(77){AD1},
			PA0(78){AD0},
			PJ7(79),
			VCC(80),
			GND(81),
			PK7(82){ADC15,PCINT23},
			PK6(83){ADC14,PCINT22},
			PK5(84){ADC13,PCINT21},
			PK4(85){ADC12,PCINT20},
			PK3(86){ADC11,PCINT19},
			PK2(87){ADC10,PCINT18},
			PK1(88){ADC9,PCINT17},
			PK0(89){ADC8,PCINT16},
			PF7(90){ADC7,TDI},
			PF6(91){ADC6,TDO},
			PF5(92){ADC5,TMS},
			PF4(93){ADC4,TCK},
			PF3(94){ADC3},
			PF2(95){ADC2},
			PF1(96){ADC1},
			PF0(97){ADC0},
			AREF(98),
			GND(99),
			AVCC(100)
		}
	}
}